project: artefacts/lite3-sdk-deploy
version: 0.1.0

jobs:
  rail_target_follow:
    type: test
    timeout: 15 # minutes
    package:
      docker:
        build:
          dockerfile: empty
    runtime:
      framework: other
      simulator: mujoco
      
    scenarios:
      settings:
        - name: test_sim_rail_target_follow_distance
          pytest_file: "src/Lite3_sdk_deploy/test/test_sim_rail_target_follow_distance.py"
          